---
- name: php70 installed
  yum:
    name: "php70,php70-mysqlnd,php70-xml,php70-mbstring,php70-mcrypt,php70-gd,php70-zip"

- name: "check {{ concrete5_path }}' if exist"
  stat:
    path: "{{ concrete5_path }}"
  register: stat_concrete5_home
- name: download concrete5
  unarchive:
    src: "{{ concrete5_download_url }}"
    dest: /opt
    remote_src: yes
    owner: apache
    group: apache
  when: stat_concrete5_home.stat.exists == false

- name: "/etc/httpd/conf.d/concrete5.conf"
  template:
    src: concrete5.conf
    dest: /etc/httpd/conf.d/concrete5.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart apache24 service
