#
# concrete5.yml
#
# ansible-playbook --extra-vars "db_user=master db_password=ChangeIt db_name=concrete5 db_endpoint=testwordpress.xxx.ap-northeast-1.rds.amazonaws.com" concrete5.yml
#
- hosts: localhost
  connection: local
  vars:
    cms_type: concrete5
  roles:
   - common
   - apache24
   - concrete5
