#
# wordpress.yml
#
# ansible-playbook --extra-vars "db_user=master db_password=ChangeIt db_name=wordpress db_endpoint=testwordpress.xxx.ap-northeast-1.rds.amazonaws.com" wordpress.yml
#
- hosts: localhost
  connection: local
  vars:
    cms_type: wordpress
  roles:
   - common
   - apache24
   - wordpress
