---
- name: mysql56-server installed
  yum:
    name: mysql56-server
- name: mysqld service started
  service:
    name: mysqld
    state: started
    enabled: yes
- name: "/etc/my.cnf"
  template:
    src: my.cnf
    dest: /etc/my.cnf
    backup: yes
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart mysqld service

